### ISSUE TITLE
Can't start due to missing Classes

### ISSUE THREAD

**Issue by Xaikii** [FrogCraft-Rebirth/FrogCraft-Rebirth#42]
java.lang.NoClassDefFoundError: frogcraftrebirth/common/item/ItemAmmoniaCoolant
	at frogcraftrebirth.common.FrogRegistries.regItem(FrogRegistries.java:130)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_272_FrogRegistries_regItem_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:739)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:603)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Caused by: java.lang.ClassNotFoundException: frogcraftrebirth.common.item.ItemAmmoniaCoolant
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 25 more
Caused by: java.lang.NoClassDefFoundError: ic2/api/reactor/IReactorComponent
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 27 more
Caused by: java.lang.ClassNotFoundException: ic2.api.reactor.IReactorComponent
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 31 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer com.bloodnbonesgaming.bnbgamingcore.core.BNBGamingCoreClassTransformer@261ea657 from coremod BNBGamingCore
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:262)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 33 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at frogcraftrebirth.common.FrogRegistries.regItem(FrogRegistries.java:130)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_272_FrogRegistries_regItem_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:739)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:603)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)

**Comment by 3TUSK** [comment]
Try updating or removing BNBGamingCore (I think it calls so) and any mods that rely on it. It looks like that it is doing something strange...

I am pretty sure the issue does not fall on my side.

**Comment by adrwa** [comment]
this issue is caused by IC2 not being installed yet the item instances an IC2 interface, you either need to supply the API with the mod, or use @Optional

**Comment by Xaikii** [comment]
Yea, adding IC2 fixes this, still wierd since it is listed as dependency but Twitch didn't downloaded IC2 aswell although it is listed as dependency

**Comment by 3TUSK** [comment]
@TheCodedOne You probably don't notice that FrogCraft: Rebirth is an IC2 add-on and has hard dependency on it... 

Edit: see below.

**Comment by 3TUSK** [comment]
Actually... the declaration of hard-dependency fails to work due to unknown reason.
I still remember that the following declaration worked at a certain moment but can't remember when:
https://github.com/FrogCraft-Rebirth/FrogCraft-Rebirth/blob/cae2b4ef711045a6fc4bb2e28a4121ea07919a7c/src/main/resources/mcmod.info#L15

Now it's a real bug...

Edit:
````json
{
  "useDependencyInformation": true
}
````

**Comment by liach** [comment]
@3TUSK You should define the dependency in `@Mod` annotation.
https://github.com/FrogCraft-Rebirth/FrogCraft-Rebirth/blob/1.12/src/main/java/frogcraftrebirth/FrogCraftRebirth.java#L43

**Comment by 3TUSK** [comment]
New release will be available at:
https://minecraft.curseforge.com/projects/frogcraft-rebirth/files/2515300

As for Twitch fails to download ic2: that issue is still out of range. I do have marked each release with IC2 as "Required Library".
