### ISSUE TITLE
java.lang.NullPointerException: Ticking block entity

### ISSUE THREAD

**Issue by 3TUSK** [FrogCraft-Rebirth/FrogCraft-Rebirth#5]
```
[19:56:18] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:709) ~[MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:614) ~[MinecraftServer.class:?]
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:118) ~[IntegratedServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:485) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:752) [MinecraftServer$2.class:?]
Caused by: java.lang.NullPointerException
    at frogcraftrewrite.common.tile.TileCondenseTower.updateEntity(TileCondenseTower.java:58) ~[TileCondenseTower.class:?]
    at net.minecraft.world.World.updateEntities(World.java:2160) ~[World.class:?]
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:515) ~[WorldServer.class:?]
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:703) ~[MinecraftServer.class:?]
    ... 4 more
```

**Comment by 3TUSK** [comment]
Won't be a lonely case. This should be a very fatal problem.

**Comment by 3TUSK** [comment]
Never mind it. You cannot create `FluidStack` from null.
