### ISSUE TITLE
Network error

### ISSUE THREAD

**Issue by 3TUSK** [FrogCraft-Rebirth/FrogCraft-Rebirth#6]
```
java.lang.NullPointerException
    at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936) ~[?:1.8.0_60]
    at java.util.concurrent.ConcurrentHashMap.containsKey(ConcurrentHashMap.java:964) ~[?:1.8.0_60]
    at cpw.mods.fml.common.network.NetworkRegistry.hasChannel(NetworkRegistry.java:276) ~[NetworkRegistry.class:?]
    at cpw.mods.fml.common.network.handshake.NetworkDispatcher.handleClientSideCustomPacket(NetworkDispatcher.java:289) ~[NetworkDispatcher.class:?]
    at cpw.mods.fml.common.network.handshake.NetworkDispatcher.channelRead0(NetworkDispatcher.java:202) ~[NetworkDispatcher.class:?]
    at cpw.mods.fml.common.network.handshake.NetworkDispatcher.channelRead0(NetworkDispatcher.java:47) ~[NetworkDispatcher.class:?]
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
    at io.netty.channel.local.LocalChannel.finishPeerRead(LocalChannel.java:313) [LocalChannel.class:?]
    at io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:43) [LocalChannel.class:?]
    at io.netty.channel.local.LocalChannel$6.run(LocalChannel.java:299) [LocalChannel$6.class:?]
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:354) [SingleThreadEventExecutor.class:?]
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:348) [NioEventLoop.class:?]
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101) [SingleThreadEventExecutor$2.class:?]
    at java.lang.Thread.run(Thra:745) [?:1.8.0_60]
```

Obviously this is an error on networking.

**Comment by 3TUSK** [comment]
Lesson: don't forge to add your channel name. i.e.: `new FMLProxyPacket(Bytebuf bytebuf, String channelName)`.
